version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    # - go download
    - go get github.com/marcboeker/go-duckdb 
    - go mod tidy

builds:
  - id: darwin-amd64
    binary: golang-cross
    env:
      - CGO_ENABLED=1
    goos:
      # duckDB-go does not support windows
      - darwin
  - id: linux-pi
    binary: golang-cross
    env:
      - GCO_ENABLED=1
    goos: 
      - linux
    
archives:
  - id: golang-cross
    builds:
      - darwin-amd64
      - linux-armhf
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
