name: goreleaser

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - v*
permissions:
   contents: write # needed to write releases

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: git fetch --prune --unshallow
      # - name: Set uo Clib build env
      #   run: |
      #     sudo apt-get update
          # sudo apt-get install gcc-multilib # install headerfiles for duckDB cgo
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: release dry run
        run: make release-dry-run
      - name: release publish
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

