name: zigrelease

# run only on tags
on:
  pull_request:
  push:
    tags:
      - 'v*'

permissions:
   contents: write # needed to write releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          apt-get update \
          apt-get gcc-arm-linux-gnueabihf
      - uses: actions/checkout@v4
        # with:
          # fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Go Releaser
        uses: goreleaser/goreleaser-action@v4          # run goreleaser
        with:
          version: latest
          args: release --clean --snapshot
        env:
          CGO_ENABLED: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
